openapi: 3.0.0
info:
  description: This is a mock implementation of external APIs for use with the Project
    Turing heist simulator
  license:
    name: Apache-2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: Project Turing APIs
  version: 1.0.0
servers:
- url: http://petstore.swagger.io/v2
paths:
  /weather:
    get:
      operationId: getWeather
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Weather'
          description: successful operation
      summary: Fetch the status of the current weather
      x-eov-operation-handler: controllers/DefaultController
components:
  schemas:
    Weather:
      description: The current status of the weather
      example:
        rain: 6
        daylight: daytime
        id: 0
      properties:
        id:
          format: int64
          type: integer
        daylight:
          description: "null"
          enum:
          - daytime
          - nighttime
          type: string
        rain:
          default: 0
          format: int32
          type: integer
      title: Weather
      type: object
