openapi: 3.0.0
servers:
  - url: "http://petstore.swagger.io/v2"
info:
  description: >-
    This is a mock implementation of external APIs for use with the Project Turing heist simulator
  version: 1.0.0
  title: Project Turing APIs
  license:
    name: Apache-2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0.html"
paths:
  /weather:
    get:
      summary: Fetch the status of the current weather
      description: ""
      operationId: getWeather
      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Weather"
components:
  schemas:
    Weather:
      title: Weather
      description: The current status of the weather
      type: object
      properties:
        id:
          type: integer
          format: int64
        daylight:
          type: string
          description:
          enum:
            - daytime
            - nighttime
        rain:
          type: integer
          format: int32
          default: 0
